### ISSUE TITLE
General question - Why use Rust instead of Kotlin

### ISSUE THREAD

**Issue by anonymous1654** [JosueMolinaMorales/mutant-kraken#30]
Just curious to know why Rust was used to write this tool, or if there were any advantages in mind. Thanks in advance

**Comment by JosueMolinaMorales** [comment]
Hey! thanks for the question. I actuallly received this question when i was defending my thesis. It's a valid question to ask.

There was not well thought out reason for choosing rust. This project stemmed from a software engineering capstone class my last semester of undergrad. My team and i decided to build a tool from the ground up instead of forking an existing tool like PIT. No of us wanted to do Java or Python and i was the only one who knew Kotlin but at the time i was very confident in Rust and suggested it to my team and we ran with it.

Since building it out though i have seen that rust has been incredibly helpful when it came to concurrency. It just made sense to me and was super easy to implement. We improved the time to generate mutants tremendously by introducing concurrency. 

Writing tests have been super easy as well within rust and the borrow checker has been a friend here more than an enemy.

Hope this answers your question! I was actually thinking of writing a blog post talking about my experience building this tool out.

@anonymous1654
